fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User
    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager  # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)
    service:
        user_manager: sonata.user.orm.user_manager
# FOSUser custom form types
#    registration:
#        form:
#            type: AppBundle\Form\RegistrationTypea.user.orm.user_manager

sonata_user:
    security_acl: true
    manager_type: orm # can be orm or mongodb

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts:   [admin]
        sonata.block.service.text: ~
        sonata.block.service.rss: ~

sonata_admin:
    title:  Content Management
#    title_logo: bundles\app\images\logo_only.png
    templates:
            search:              SonataAdminBundle:Core:search.html.twig
            search_result_block: SonataAdminBundle:Block:block_search_result.html.twig
    dashboard:
            groups:
                admin.group.product:
                    label: admin.group.product
                    label_catalogue: SonataAdminBundle
                    items:
                        - sonata.admin.product
                        - sonata.admin.category
                admin.group.user:
                    label: admin.group.user
                    label_catalogue: SonataAdminBundle
                    items:
                        - sonata.user.admin.user
                        - sonata.user.admin.group
                    roles: [ ROLE_ADMIN ]
            blocks:
                -
                    position: left
                    type: sonata.admin.block.admin_list
                -
                    position: right
                    type: sonata.block.service.text
                    settings:
                        content: >
                            <h3>CM News:</h3>
                            <p>Manages all web content and projects related to the website. Writes,
                            edits, and proofreads new content. Ensures that all documents meet established
                            content standards and works with developers to assess any technical challenges
                            in displaying the content. Requires a bachelor's degree in a related area and at
                            least 7 years of experience in the field or in a related area. Familiar with a
                            variety of the field's concepts, practices, and procedures. Relies on extensive
                            experience and judgment to plan and accomplish goals. Performs a variety of tasks.
                            Leads and directs the work of others. A wide degree of creativity and latitude is
                            expected. Typically reports to top management.</p>
                -
                    position: right
                    type: sonata.block.service.rss
                    settings:
                        title: Sonata Project's Feeds
                        url: http://sonata-project.org/blog/archive.rss