nelmio_api_doc: ~

lexik_jwt_authentication:
    private_key_path: '%kernel.root_dir%/../var/jwt/private.pem'
    public_key_path:  '%kernel.root_dir%/../var/jwt/public.pem'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        3600

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: 'KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig'     # sliding pagination controls template
        sortable: 'KnpPaginatorBundle:Pagination:sortable_link.html.twig' # sort link template

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User
    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager  # use sonata.user.mongodb.group_manager for mongodb
    service:
        user_manager: sonata.user.orm.user_manager
# FOSUser custom form types
#    registration:
#        form:
#            type: AppBundle\Form\RegistrationTypea.user.orm.user_manager

sonata_user:
    security_acl: true # using acl to prevent normal user to change settings of super-admin users
    manager_type: orm  # can be orm or mongodb

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts:   [admin]
        sonata.block.service.text: ~
        sonata.block.service.rss: ~

# custom sonata orm admin templates & custom image form field type
# for show and list, show/edit.
# implemented via form field type extensions)
sonata_doctrine_orm_admin:
    templates:
        types:
            show:
                image: :admin:show_image.html.twig
            list:
                image: :admin:list_image.html.twig

# sonata admin area
sonata_admin:
    title:  Acme CMS
    title_logo: images\logo.png
    security:
        handler: sonata.admin.security.handler.acl
        # acl security information
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]
    templates:
            search:              SonataAdminBundle:Core:search.html.twig
            search_result_block: SonataAdminBundle:Block:block_search_result.html.twig
    dashboard:
            groups:
                admin.group.solution:
                    label: admin.group.solution
                    label_catalogue: SonataAdminBundle
                    items:
                        - app.admin.solution
                admin.group.product:
                    label: admin.group.product
                    label_catalogue: SonataAdminBundle
                    items:
                        - app.admin.category
                        - app.admin.product
                        - app.admin.product_image
                admin.group.user:
                    label: admin.group.user
                    label_catalogue: SonataAdminBundle
                    items:
                        - sonata.user.admin.user
                        - sonata.user.admin.group
            blocks:
                -
                    position: left
                    type: sonata.admin.block.admin_list
                -
                    position: right
                    type: sonata.block.service.text
                    settings:
                        content: >
                            <h3>CM News:</h3>
                            <p>Manages all web content and projects related to the website. Writes,
                            edits, and proofreads new content. Ensures that all documents meet established
                            content standards and works with developers to assess any technical challenges
                            in displaying the content. Requires a bachelor's degree in a related area and at
                            least 7 years of experience in the field or in a related area. Familiar with a
                            variety of the field's concepts, practices, and procedures. Relies on extensive
                            experience and judgment to plan and accomplish goals. Performs a variety of tasks.
                            Leads and directs the work of others. A wide degree of creativity and latitude is
                            expected. Typically reports to top management.</p>
                -
                    position: right
                    type: sonata.block.service.rss
                    settings:
                        title: Sonata Project's Feeds
                        url: http://sonata-project.org/blog/archive.rss