services:
    app.utils:
        class: AppBundle\Utils\Utils

    app.doctrine.entity_slugify_listener:
        class: AppBundle\Doctrine\EntitySlugifyListener
        arguments: ["@app.utils"]
        tags:
            - { name: doctrine.event_subscriber }

#    SonataAdminBundle services
    sonata.admin.product:
            class: AppBundle\Admin\ProductAdmin
            arguments: [~, AppBundle\Entity\Product, ~]
            tags:
                - name: sonata.admin
                  manager_type: orm
                  group: "admin.group.item"
                  label: "admin.model.product"
#            calls:
#                - [ setTranslationDomain, [SonataAdminBundle]]

    sonata.admin.category:
            class: AppBundle\Admin\CategoryAdmin
            arguments: [~, AppBundle\Entity\Category, ~]
            tags:
                - name: sonata.admin
                  manager_type: orm
                  group: "admin.group.item"
                  label: "admin.model.category"
#            calls:
#                - [ setTranslationDomain, [SonataAdminBundle]]