services:
    app.utils:
        class: AppBundle\Utils\Utils

    app.doctrine.entity_slugify_listener:
        class: AppBundle\Doctrine\EntitySlugifyListener
        arguments: ["@app.utils"]
        tags:
            - { name: doctrine.event_subscriber }
