services:
    app.utils:
        class: AppBundle\Utils\Utils

    app.uploader:
        class: AppBundle\Utils\FileUploader
        arguments: ["%upload_folder%"]

    app.fixture_loader:
        class: AppBundle\Utils\FixtureLoader
        arguments: ["@service_container"]

#   Twig Extension
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        autowire: true
        public: false
        tags:
            - { name: twig.extension }

#   Menu Builders
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@doctrine.orm.entity_manager"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main_menu }
            - { name: knp_menu.menu_builder, method: createSubMenuFromEntity, alias: entity_sub_menu }

#   Form Field Type Extensions
    app.image_type_extension:
        class: AppBundle\Form\Extension\ImageTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }

#   Doctrine Listeners
    app.doctrine.entity_slugify_listener:
        class: AppBundle\Doctrine\EntitySlugifyListener
        arguments: ["@app.utils"]
        tags:
            - { name: doctrine.event_subscriber }

    app.doctrine.entity_file_upload_listner:
        class: AppBundle\Doctrine\FileUploadListener
        arguments: ["@app.uploader"]
        tags:
            - { name: doctrine.event_subscriber }

#    Sonata Admin services
    app.admin.solution:
            class: AppBundle\Admin\SolutionAdmin
            arguments: [~, AppBundle\Entity\Solution, ~]
            tags:
                - name: sonata.admin
                  manager_type: orm
                  group: "admin.group.solution"
                  label: "admin.model.solution"
#            calls:
#                - [ setTranslationDomain, [SonataAdminBundle]]

    app.admin.category:
            class: AppBundle\Admin\CategoryAdmin
            arguments: [~, AppBundle\Entity\Category, ~]
            tags:
                - name: sonata.admin
                  manager_type: orm
                  group: "admin.group.item"
                  label: "admin.model.category"

    app.admin.product:
            class: AppBundle\Admin\ProductAdmin
            arguments: [~, AppBundle\Entity\Product, ~]
            tags:
                - name: sonata.admin
                  manager_type: orm
                  group: "admin.group.item"
                  label: "admin.model.product"

    app.admin.product_image:
            class: AppBundle\Admin\ProductImageAdmin
            arguments: [~, AppBundle\Entity\ProductImage, ~]
            tags:
                - name: sonata.admin
                  manager_type: orm
                  group: "admin.group.item"
                  label: "admin.model.pimages"

parameters:
    security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap
